In [3]:
print("Hello")

Hello


In [4]:
import numpy as np

In [5]:
a = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[5,6],[7,8]],
    [[5,6],[7,8]]
])

In [6]:
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[5 6]
  [7 8]]

 [[5 6]
  [7 8]]]


In [7]:
b = np.array([[1,2,3],[1,2,3]])

In [8]:
print(b.ndim)

2


In [9]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [11]:
d=np.arange(1,13).reshape(2,-1)
d

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [12]:
d.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [13]:
d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
e=np.array([20,30,40,50])

In [15]:
f=np.array([1,2,3,4])

# Operations

In [16]:
e**2

array([ 400,  900, 1600, 2500])

In [17]:
e+f

array([21, 32, 43, 54])

In [18]:
e*f

array([ 20,  60, 120, 200])

In [19]:
e-f

array([19, 28, 37, 46])

In [20]:
e//f

array([20, 15, 13, 12])

In [21]:
l=np.array([
    [1,2,3],
    [4,5,6]
])

In [22]:
l.sum(axis=0)

array([5, 7, 9])

In [23]:
l.sum(axis=1)

array([ 6, 15])

# Zeros and Ones

In [24]:
arr1 = np.zeros((100, 4))
print(arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0.

In [25]:
arr = np.ones((100, 4))

print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1.

In [26]:
w=np.array([1,2,3],dtype=np.int64)
w

array([1, 2, 3], dtype=int64)

In [27]:
x=np.array([1,2,3],dtype=np.float64)
x.dtype.name

'float64'

In [28]:
t=np.arange(10)**3
t

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

# Indexing and Slicing

In [29]:
t[2]

np.int32(8)

In [30]:
t[2:5]

array([ 8, 27, 64], dtype=int32)

In [31]:
t[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [32]:
p=np.arange(20).reshape(5,4)
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [33]:
p[2]

array([ 8,  9, 10, 11])

In [34]:
p[0:1,1]#col ko arrange ma karte ha

array([1])

In [35]:
p[1]

array([4, 5, 6, 7])

In [36]:
np.hstack((e,f))

array([20, 30, 40, 50,  1,  2,  3,  4])

In [37]:
np.vstack((e,f))

array([[20, 30, 40, 50],
       [ 1,  2,  3,  4]])

# Splitting

In [38]:
q=np.arange(0,24).reshape(2,12)
q

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [39]:
np.hsplit(q,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [12, 13, 14, 15, 16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [18, 19, 20, 21, 22, 23]])]

In [40]:
np.vsplit(q,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])]

# Broadcasting

In [41]:
#two d.f dimension
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])  
arr_1d = np.array([10, 20, 30])              

result = arr_2d + arr_1d
print(result)

[[11 22 33]
 [14 25 36]]


In [42]:
#scalar
arr = np.array([1, 2, 3])
result = arr + 5

print(result)

[6 7 8]


In [43]:
# column matrix
arr5 = np.array([[1],[2],[3],[4],[5]])
print(arr5)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [44]:
arr6 = arr5 + arr
print(arr6)

[[2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


# TASK 1

In [45]:
a1= np.random.rand(100000)

In [46]:
def solve(x):
    return 3*x**2 + 2*x + 1
solve(a1)

array([3.90782349, 5.98483005, 5.02233915, ..., 5.65449661, 3.37353025,
       3.72275385], shape=(100000,))

In [ ]:
import timeit

execution_time = timeit.timeit('solve(a1)', globals=globals(), number=100000)
print(execution_time)

we have to make two input vector with 1000 features each and then cal euclidean distance and compare the time result with the list's result